[pytest]
#addopts = -v -s --alluredir=allure-results
addopts = -v -s
testpaths = Tests
python_files = test_*.py
log_cli = true
log_cli_level = INFO

markers =
    smoke: fast tests for critical functionality
    regression: full test suite
    api: All API tests
    ui: All UI tests

    #Tests for specific API
    fakestore: tests for FakeStore API
    restulbooker: test for RestfulBooker API